// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqlcnvdraewntjlwwhzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxbGNudmRyYWV3bnRqbHd3aHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTI5MzEsImV4cCI6MjA2OTg4ODkzMX0.A6qSESPj2UDW9ElO3vhF_Djr81GfPRwsGSQAh7wP4cI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});